---
abstract: 'Peek into archives without extracting them (using libarchive)'
author:
  - 'Leon Brocard <acme@astray.com>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Archive-Peek-Libarchive
provides:
  Archive::Peek::Libarchive:
    file: lib/Archive/Peek/Libarchive.pm
    version: 0.35
requires:
  Object::Tiny: 0
  Test::More: 0
resources:
  homepage: http://search.cpan.org/dist/Archive-Peek-Libarchive/
  license: http://dev.perl.org/licenses/
version: 0.35
